pull_request_rules:
  - name: Automatic merge for dependabot PRs
    conditions:
      - "#approved-reviews-by>=1"
      - author~=^dependabot(|-preview)\[bot\]$
      - "status-success=continuous-integration/appveyor/pr"
      - "status-success=continuous-integration/travis-ci/pr"
      - "status-success=continuous-integration/travis-ci/push"
    actions:
      merge:
        method: merge
        strict_method: rebase
        strict: true
