language: node_js
node_js:
  - "node"
env:
  global:
    secure: g9BqtXjvVNNvF9lddICMaGnVGkG4ZwJUcC7KcShS8J7/UYx0WSmWvpelMFWzY71Tt7NlohWJGccXT4Qcs1uK76VgBSbjjGuX1EMSEPdYjfgWhpzBZo3NBslMQaEbet26f0UoPvIN18E0OAw3raer41ng4S7ZMmuHhIdw0i1Z7QuGwlDDEO+sLIjiSyYd0fqCDRYe3G4TEA6Ju1r8aw5JvkLozHItZNOF1s2vOA8wtJd0Y5PeBYEV1HbBA2TSZJJyHbNUuan1nqcb/hNyLYCcl+qve4H08g4zEGQR9MgD1AXp68zRzQ1QAhMA1VkUFv0yN6N+0Gl+E871euJcaX/wlYZMQb1DhY/0cvgVR1+orbSYVuL91INJAguQIGByy3EexMLNFpjnNpCPR4RalioPrBUYZrtijgWvH1WE3nfk2UJBlUwDXcLq7IBc91jba3g+vdwPJwATglRszNAraCeSrgx5y5ccuf/wejc/DD2G9i8dxqd/qVr+gjagzrwxQxq5GpKLqDtZLV3kASBcjdepEqbZ511Cm60PdfSNK6xwfiM31iDVb7l7+xywQAJSgGQMjAslsLGa1Mhw6PBsercXOp3uZZyc5/JqHyc0iIpGFBlDj7BZMwDbailylAHl9zcqyrJsHbiJ8QR6XlOF+/h3bWsfdLHhEIO3/z0M4EHusYQ=
