version: "{build}"

environment:
  nodejs_version: "6"
  SNYK_TOKEN:
    secure: 2HH1+J++C/e7GSlklkVgJJhL+2EMiqq73aDu/PyU7O5EECduDRxm9qFfrZFf9HmH

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off

branches:

  only:

  - master

clone_depth: 1
