version: "{build}"

environment:
  nodejs_version: 12

install:
  - ps: Install-Product node $env:nodejs_version
  - npm ci

cache:
  - "%APPDATA%\\npm-cache"

test_script:
  - node --version
  - npm --version
  - npm test

build: off

branches:

  only:

  - master

clone_depth: 1
