name: Continuous Integration

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  test_node:
    name: Node CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install Node Dependencies
      run: npm ci
    - name: Run Tests
      run: npm test
